# Generated by Django 4.2.4 on 2023-08-05 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
                ('createDateTime', models.DateTimeField(auto_now_add=True)),
                ('updateDateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColorOptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('hashCode', models.CharField(max_length=20)),
                ('createDateTime', models.DateTimeField(auto_now_add=True)),
                ('updateDateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneTypeOptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('createDateTime', models.DateTimeField(auto_now_add=True)),
                ('updateDateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SizeOptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('sizeCode', models.CharField(max_length=20)),
                ('createDateTime', models.DateTimeField(auto_now_add=True)),
                ('updateDateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('token', models.CharField(max_length=200)),
                ('createDateTime', models.DateTimeField(auto_now_add=True)),
                ('updateDateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('basePrice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('printPrice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discountPrice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('in_stock', models.BooleanField(default=True)),
                ('colorOtions', models.JSONField(blank=True, null=True)),
                ('sizeOptions', models.JSONField(blank=True, null=True)),
                ('phoneTypeOptions', models.JSONField(blank=True, null=True)),
                ('createDateTime', models.DateTimeField(auto_now_add=True)),
                ('updateDateTime', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.category')),
            ],
        ),
        migrations.CreateModel(
            name='GenDesign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('prompt', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('createDateTime', models.DateTimeField(auto_now_add=True)),
                ('updateDateTime', models.DateTimeField(auto_now=True)),
                ('userDevice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.userdevice')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('createDateTime', models.DateTimeField(auto_now_add=True)),
                ('updateDateTime', models.DateTimeField(auto_now=True)),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.gendesign')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.product')),
                ('userDevice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.userdevice')),
            ],
        ),
    ]
