# Generated by Django 4.2.4 on 2023-10-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_product_colorotions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colorOtions',
            field=models.ManyToManyField(blank=True, null=True, to='API.coloroptions'),
        ),
        migrations.AlterField(
            model_name='product',
            name='phoneTypeOptions',
            field=models.ManyToManyField(blank=True, null=True, to='API.phonetypeoptions'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizeOptions',
            field=models.ManyToManyField(blank=True, null=True, to='API.sizeoptions'),
        ),
    ]
