# Generated by Django 4.2.4 on 2023-10-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_product_colorotions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonetypeoptions',
            name='modelCode',
            field=models.CharField(default='iPhone', max_length=20),
            preserve_default=False,
        ),
    ]
