# Generated by Django 4.2.4 on 2023-10-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_rename_colorotions_product_coloroptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='in_stock',
            new_name='inStock',
        ),
    ]
